name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build: node-16, ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Versions
        run: |
          echo "yarn: $(yarn --version)"
          echo "npm : $(npm --version)"
          echo "node: $(node --version)"
          echo "process.versions:"
          yarn node -p process.versions
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Audit production
        run: yarn audit --prod

      - name: Audit all
        continue-on-error: true
        run: yarn audit